[tool.ruff]
# Do not enforce line length; black does this for code and we do not care about comments / docs
ignore = ["E501"]

[tool.pytest.ini_options]
addopts = "--cov"
testpaths = [
    "tests"
]
filterwarnings = [
    "ignore::DeprecationWarning"
]
