name: Release Drafter
on:
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
